<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Assets
    |--------------------------------------------------------------------------
    */

    'title' => 'Assets',
    'subtitle' => 'Manage all company assets.',

    'add' => 'Add Asset',

    'export_pdf' => 'Export PDF',
    'export_excel' => 'Export Excel',

    'search' => 'Search...',

    'all_categories' => 'All Categories',
    'all_suppliers' => 'All Suppliers',
    'all_status' => 'All Status',

    'available' => 'Available',
    'assigned' => 'Assigned',
    'maintenance' => 'Maintenance',
    'retired' => 'Retired',

    'filter' => 'Filter',
    'reset' => 'Reset',

    /*
    |--------------------------------------------------------------------------
    | Table
    |--------------------------------------------------------------------------
    */

    'image' => 'Image',
    'code' => 'Code',
    'name' => 'Name',
    'serial' => 'Serial Number',
    'category' => 'Category',
    'supplier' => 'Supplier',
    'status' => 'Status',
    'warranty' => 'Warranty',
    'location' => 'Location',
    'actions' => 'Actions',

    /*
    |--------------------------------------------------------------------------
    | Buttons
    |--------------------------------------------------------------------------
    */

    'edit' => 'Edit',
    'delete' => 'Delete',
    'history' => 'History',
    'qr' => 'QR',

    /*
    |--------------------------------------------------------------------------
    | Messages
    |--------------------------------------------------------------------------
    */

    'confirm_delete' => 'Delete this asset?',
    'empty' => 'No assets found.',


    'create_title' => 'Create Asset',
    'create_subtitle' => 'Add a new asset to the inventory.',

    'none' => 'None',

    'purchase_date' => 'Purchase Date',
    'warranty_end' => 'Warranty End',
    'purchase_price' => 'Purchase Price',

    'save' => 'Save Asset',
    'cancel' => 'Cancel',

    'edit_title' => 'Edit Asset',
    'edit_subtitle' => 'Update asset information.',
    'current_image' => 'Current Image',
    'upload_image' => 'Upload New Image',
    'update' => 'Update Asset',

    'system' => 'Asset Management System',
    'report' => 'Assets Report',
    'generated_by' => 'Generated by Asset Management System',
    'no_assets' => 'No assets found.',

    'qr_code' => 'Asset QR Code',
    'qr_description' => 'Scan this QR code to view asset information.',
    'print' => 'Print',
    'back_assets' => 'Back to Assets',

    /*
    |--------------------------------------------------------------------------
    | Assignments
    |--------------------------------------------------------------------------
    */

    'assignments_title' => 'Asset Assignments',
    'assignments_subtitle' => 'Manage asset assignments for employees.',

    'assign_asset' => 'Assign Asset',
    'assign_asset_description' => 'Assign an asset to a user.',

    'asset' => 'Asset',
    'user' => 'User',
    'assigned_date' => 'Assigned Date',
    'returned_date' => 'Returned Date',

    'edit_assignment' => 'Edit Assignment',
    'edit_assignment_description' => 'Update asset assignment information.',
    'update_assignment' => 'Update Assignment',

];
